app = "cashazo-admin"
primary_region = "sjc"

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
SUPABASE_URL = "https://heljnwezenhdaxjcevti.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbGpud2V6ZW5oZGF4amNldnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyNTcyNzMsImV4cCI6MjEwMzgzMzI3M30.4Ri1SUroyhJVB4hueroF8-aM8YsRadeCsLkGcOxKwDM"

[[services]]
internal_port = 3000
processes = ["app"]
protocol = "tcp"

[services.concurrency]
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
interval = "15s"
timeout = "5s"
grace_period = "5s"
max_retries = 3
