# fly.toml file generated for cashazo-admin
app = "cashazo-admin"
primary_region = "sjc"

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"
SUPABASE_URL = "https://heljnwezenhdaxjcevti.supabase.co"
SUPABASE_KEY = "sb_publishable_JEl1Zq6hs0sbGQ32Y1uzaA_7Px1gXkq"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
processes = ["app"]

[[stickiness]]
header = "Cookie"